"""Conversion of review results into GitHub review comments and step summaries."""

from __future__ import annotations

from tools.ai_review.models import Finding, Review, REVIEW_MARKER

COMMENT_BODY_CAP = 65_000
REVIEW_BODY_CAP = 65_000


def anchor_findings(
    findings: list[Finding],
    anchors: dict,
) -> tuple[list[Finding], list[Finding]]:
    """Split findings into inline-commentable and summary-only ones.

    A finding is inline-commentable when its file and line resolve to a line
    that exists in the new-file diff. Everything else (wrong file, removed
    line, patched-in line number mismatch) is moved into the review body so the
    GitHub API never receives an invalid ``line`` value.
    """
    inline: list[Finding] = []
    unanchored: list[Finding] = []
    for finding in findings:
        patch = anchors.get(finding.file)
        if patch is not None and patch.anchors_line(finding.line):
            inline.append(finding)
        else:
            unanchored.append(finding)
    return inline, unanchored


def render_finding_body(finding: Finding) -> str:
    body = f"**[{finding.severity}] {finding.category}** - {finding.title}\n\n{finding.body}"
    if len(body) > COMMENT_BODY_CAP:
        body = body[: COMMENT_BODY_CAP - 1] + "\u2026"
    return body


def build_inline_comments(findings: list[Finding]) -> list[dict]:
    return [
        {
            "path": finding.file,
            "line": finding.line,
            "side": "RIGHT",
            "body": render_finding_body(finding),
        }
        for finding in findings
    ]


def build_review_body(
    *,
    summary: str,
    unanchored: list[Finding],
    notes: list[str],
    model: str,
    reviewed_count: int,
    skipped_names: list[str],
) -> str:
    lines = [
        f"**{REVIEW_MARKER} - automated and does not block merge.**",
        "",
        f"Generated by `{model}` on a GitHub-hosted runner. This review is "
        "advisory only and is not a substitute for human review. Pull request "
        "content was treated as untrusted data.",
        "",
        "## Summary",
        "",
        summary,
    ]
    if unanchored:
        lines += ["", "## Findings without a diff anchor"]
        lines += [
            "",
            "These findings could not be placed on a valid diff line and are listed here:",
        ]
        for finding in unanchored:
            lines.append(
                f"- `{finding.file}` (around line {finding.line}) - "
                f"**[{finding.severity}] {finding.category}** {finding.title}: "
                f"{finding.body}"
            )
    if notes:
        lines += ["", "## Review notes", ""]
        lines += [f"- {note}" for note in notes]
    footer = [f"- Reviewed {reviewed_count} file(s)."]
    if skipped_names:
        shown = ", ".join(skipped_names[:8])
        more = f" (+{len(skipped_names) - 8} more)" if len(skipped_names) > 8 else ""
        footer.append(f"- Excluded {len(skipped_names)} file(s) as generated/binary/large: {shown}{more}")
    lines += ["", "### Scope"] + footer

    body = "\n".join(lines)
    if len(body) > REVIEW_BODY_CAP:
        body = body[: REVIEW_BODY_CAP - 1] + "\u2026"
    return body


def can_post_pr_review(pull: dict) -> bool:
    """Whether the workflow token can realistically post a review.

    On fork pull requests and Dependabot pull requests the ``pull_request``
    workflow runs with a read-only token, so the review is written to the step
    summary instead of posted. This is checked before attempting to post; a
    403 still falls back to the summary path.
    """
    user = (pull.get("user") or {}).get("login")
    if user == "dependabot[bot]":
        return False
    head = pull.get("head") or {}
    if (head.get("repo") or {}).get("fork"):
        return False
    return True


def write_step_summary(path: str | None, markdown: str) -> None:
    """Append ``markdown`` to a job-step summary file or print it to stdout."""
    if not path:
        print(markdown)
        return
    with open(path, "a", encoding="utf-8") as handle:
        handle.write(markdown.strip() + "\n")